version: "3.8"
services:
  emqx:
    container_name: emqx
    image: emqx/emqx:5.0.16
    restart: always
    ports:
      - 1883:1883
      - 8083:8083
      - 18083:18083
  
  nodered:
    container_name: node-red
    image: nodered/node-red:2.2.3
    restart: always
    ports:
      - 1880:1880
    volumes:
      - ./nodered/:/data